name: Backend Build and Test

on:
  push:
    branches:
      - backend # Trigger on push to the backend branch

jobs:
  build:
    runs-on: ubuntu-latest # use the latest version of Ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2 # set up Python
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip # upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Unit Tests
        run: |
          pytest tests/ # run unit tests
