name: Pre-Merge Validation

on:
  pull_request:
    branches:
      - main # trigger on pull requests to the main branch

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # checkout the code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies # install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests # unit testing
        run: |
          pytest tests/
